/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.onesite.sdk.thrift.dao.constants;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum BirthdayDisplay implements org.apache.thrift.TEnum {
  FULL(0),
  BIRTHDAY_ONLY(1),
  AGE_ONLY(2),
  OWNER(3),
  FRIENDS(4);

  private final int value;

  private BirthdayDisplay(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static BirthdayDisplay findByValue(int value) { 
    switch (value) {
      case 0:
        return FULL;
      case 1:
        return BIRTHDAY_ONLY;
      case 2:
        return AGE_ONLY;
      case 3:
        return OWNER;
      case 4:
        return FRIENDS;
      default:
        return null;
    }
  }
}
