/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.onesite.sdk.thrift.dao.constants;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CommentsApproval implements org.apache.thrift.TEnum {
  MANUALLY(0),
  AUTO_APPROVE_ALL(1),
  AUTO_APPROVE_FRIENDS_ONLY(2);

  private final int value;

  private CommentsApproval(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CommentsApproval findByValue(int value) { 
    switch (value) {
      case 0:
        return MANUALLY;
      case 1:
        return AUTO_APPROVE_ALL;
      case 2:
        return AUTO_APPROVE_FRIENDS_ONLY;
      default:
        return null;
    }
  }
}
