/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.onesite.sdk.thrift.dao.constants;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EmailNotification implements org.apache.thrift.TEnum {
  NONE(0),
  DAILY(1),
  WEEKLY(2),
  ONGOING(3);

  private final int value;

  private EmailNotification(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EmailNotification findByValue(int value) { 
    switch (value) {
      case 0:
        return NONE;
      case 1:
        return DAILY;
      case 2:
        return WEEKLY;
      case 3:
        return ONGOING;
      default:
        return null;
    }
  }
}
