/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.onesite.sdk.thrift.dao.constants;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum GroupMemberStatus implements org.apache.thrift.TEnum {
  PENDING(0),
  MEMBER(1),
  MODERATOR(2),
  OWNER(3),
  INVITED(4),
  BANNED(5);

  private final int value;

  private GroupMemberStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GroupMemberStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return PENDING;
      case 1:
        return MEMBER;
      case 2:
        return MODERATOR;
      case 3:
        return OWNER;
      case 4:
        return INVITED;
      case 5:
        return BANNED;
      default:
        return null;
    }
  }
}
