/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.onesite.sdk.thrift.api;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ResponseExternalProperty implements org.apache.thrift.TBase<ResponseExternalProperty, ResponseExternalProperty._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ResponseExternalProperty");

  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField EXTERNAL_PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("externalProperty", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ResponseExternalPropertyStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ResponseExternalPropertyTupleSchemeFactory());
  }

  public Status status; // required
  public com.onesite.sdk.thrift.dao.ExternalProperty externalProperty; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STATUS((short)1, "status"),
    EXTERNAL_PROPERTY((short)2, "externalProperty");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STATUS
          return STATUS;
        case 2: // EXTERNAL_PROPERTY
          return EXTERNAL_PROPERTY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Status.class)));
    tmpMap.put(_Fields.EXTERNAL_PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("externalProperty", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.onesite.sdk.thrift.dao.ExternalProperty.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ResponseExternalProperty.class, metaDataMap);
  }

  public ResponseExternalProperty() {
  }

  public ResponseExternalProperty(
    Status status,
    com.onesite.sdk.thrift.dao.ExternalProperty externalProperty)
  {
    this();
    this.status = status;
    this.externalProperty = externalProperty;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ResponseExternalProperty(ResponseExternalProperty other) {
    if (other.isSetStatus()) {
      this.status = new Status(other.status);
    }
    if (other.isSetExternalProperty()) {
      this.externalProperty = new com.onesite.sdk.thrift.dao.ExternalProperty(other.externalProperty);
    }
  }

  public ResponseExternalProperty deepCopy() {
    return new ResponseExternalProperty(this);
  }

  @Override
  public void clear() {
    this.status = null;
    this.externalProperty = null;
  }

  public Status getStatus() {
    return this.status;
  }

  public ResponseExternalProperty setStatus(Status status) {
    this.status = status;
    return this;
  }

  public void unsetStatus() {
    this.status = null;
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return this.status != null;
  }

  public void setStatusIsSet(boolean value) {
    if (!value) {
      this.status = null;
    }
  }

  public com.onesite.sdk.thrift.dao.ExternalProperty getExternalProperty() {
    return this.externalProperty;
  }

  public ResponseExternalProperty setExternalProperty(com.onesite.sdk.thrift.dao.ExternalProperty externalProperty) {
    this.externalProperty = externalProperty;
    return this;
  }

  public void unsetExternalProperty() {
    this.externalProperty = null;
  }

  /** Returns true if field externalProperty is set (has been assigned a value) and false otherwise */
  public boolean isSetExternalProperty() {
    return this.externalProperty != null;
  }

  public void setExternalPropertyIsSet(boolean value) {
    if (!value) {
      this.externalProperty = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((Status)value);
      }
      break;

    case EXTERNAL_PROPERTY:
      if (value == null) {
        unsetExternalProperty();
      } else {
        setExternalProperty((com.onesite.sdk.thrift.dao.ExternalProperty)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STATUS:
      return getStatus();

    case EXTERNAL_PROPERTY:
      return getExternalProperty();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STATUS:
      return isSetStatus();
    case EXTERNAL_PROPERTY:
      return isSetExternalProperty();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ResponseExternalProperty)
      return this.equals((ResponseExternalProperty)that);
    return false;
  }

  public boolean equals(ResponseExternalProperty that) {
    if (that == null)
      return false;

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (!this.status.equals(that.status))
        return false;
    }

    boolean this_present_externalProperty = true && this.isSetExternalProperty();
    boolean that_present_externalProperty = true && that.isSetExternalProperty();
    if (this_present_externalProperty || that_present_externalProperty) {
      if (!(this_present_externalProperty && that_present_externalProperty))
        return false;
      if (!this.externalProperty.equals(that.externalProperty))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_status = true && (isSetStatus());
    builder.append(present_status);
    if (present_status)
      builder.append(status);

    boolean present_externalProperty = true && (isSetExternalProperty());
    builder.append(present_externalProperty);
    if (present_externalProperty)
      builder.append(externalProperty);

    return builder.toHashCode();
  }

  public int compareTo(ResponseExternalProperty other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ResponseExternalProperty typedOther = (ResponseExternalProperty)other;

    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(typedOther.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, typedOther.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExternalProperty()).compareTo(typedOther.isSetExternalProperty());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExternalProperty()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.externalProperty, typedOther.externalProperty);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ResponseExternalProperty(");
    boolean first = true;

    sb.append("status:");
    if (this.status == null) {
      sb.append("null");
    } else {
      sb.append(this.status);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("externalProperty:");
    if (this.externalProperty == null) {
      sb.append("null");
    } else {
      sb.append(this.externalProperty);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ResponseExternalPropertyStandardSchemeFactory implements SchemeFactory {
    public ResponseExternalPropertyStandardScheme getScheme() {
      return new ResponseExternalPropertyStandardScheme();
    }
  }

  private static class ResponseExternalPropertyStandardScheme extends StandardScheme<ResponseExternalProperty> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ResponseExternalProperty struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.status = new Status();
              struct.status.read(iprot);
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EXTERNAL_PROPERTY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.externalProperty = new com.onesite.sdk.thrift.dao.ExternalProperty();
              struct.externalProperty.read(iprot);
              struct.setExternalPropertyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ResponseExternalProperty struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.status != null) {
        oprot.writeFieldBegin(STATUS_FIELD_DESC);
        struct.status.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.externalProperty != null) {
        oprot.writeFieldBegin(EXTERNAL_PROPERTY_FIELD_DESC);
        struct.externalProperty.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ResponseExternalPropertyTupleSchemeFactory implements SchemeFactory {
    public ResponseExternalPropertyTupleScheme getScheme() {
      return new ResponseExternalPropertyTupleScheme();
    }
  }

  private static class ResponseExternalPropertyTupleScheme extends TupleScheme<ResponseExternalProperty> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ResponseExternalProperty struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetStatus()) {
        optionals.set(0);
      }
      if (struct.isSetExternalProperty()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetStatus()) {
        struct.status.write(oprot);
      }
      if (struct.isSetExternalProperty()) {
        struct.externalProperty.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ResponseExternalProperty struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.status = new Status();
        struct.status.read(iprot);
        struct.setStatusIsSet(true);
      }
      if (incoming.get(1)) {
        struct.externalProperty = new com.onesite.sdk.thrift.dao.ExternalProperty();
        struct.externalProperty.read(iprot);
        struct.setExternalPropertyIsSet(true);
      }
    }
  }

}

