/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.onesite.sdk.thrift.api;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ResponseExternalAccount implements org.apache.thrift.TBase<ResponseExternalAccount, ResponseExternalAccount._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ResponseExternalAccount");

  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField EXTERNAL_ACCOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("externalAccount", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ResponseExternalAccountStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ResponseExternalAccountTupleSchemeFactory());
  }

  public Status status; // required
  public com.onesite.sdk.thrift.dao.ExternalAccount externalAccount; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STATUS((short)1, "status"),
    EXTERNAL_ACCOUNT((short)2, "externalAccount");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STATUS
          return STATUS;
        case 2: // EXTERNAL_ACCOUNT
          return EXTERNAL_ACCOUNT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Status.class)));
    tmpMap.put(_Fields.EXTERNAL_ACCOUNT, new org.apache.thrift.meta_data.FieldMetaData("externalAccount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.onesite.sdk.thrift.dao.ExternalAccount.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ResponseExternalAccount.class, metaDataMap);
  }

  public ResponseExternalAccount() {
  }

  public ResponseExternalAccount(
    Status status,
    com.onesite.sdk.thrift.dao.ExternalAccount externalAccount)
  {
    this();
    this.status = status;
    this.externalAccount = externalAccount;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ResponseExternalAccount(ResponseExternalAccount other) {
    if (other.isSetStatus()) {
      this.status = new Status(other.status);
    }
    if (other.isSetExternalAccount()) {
      this.externalAccount = new com.onesite.sdk.thrift.dao.ExternalAccount(other.externalAccount);
    }
  }

  public ResponseExternalAccount deepCopy() {
    return new ResponseExternalAccount(this);
  }

  @Override
  public void clear() {
    this.status = null;
    this.externalAccount = null;
  }

  public Status getStatus() {
    return this.status;
  }

  public ResponseExternalAccount setStatus(Status status) {
    this.status = status;
    return this;
  }

  public void unsetStatus() {
    this.status = null;
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return this.status != null;
  }

  public void setStatusIsSet(boolean value) {
    if (!value) {
      this.status = null;
    }
  }

  public com.onesite.sdk.thrift.dao.ExternalAccount getExternalAccount() {
    return this.externalAccount;
  }

  public ResponseExternalAccount setExternalAccount(com.onesite.sdk.thrift.dao.ExternalAccount externalAccount) {
    this.externalAccount = externalAccount;
    return this;
  }

  public void unsetExternalAccount() {
    this.externalAccount = null;
  }

  /** Returns true if field externalAccount is set (has been assigned a value) and false otherwise */
  public boolean isSetExternalAccount() {
    return this.externalAccount != null;
  }

  public void setExternalAccountIsSet(boolean value) {
    if (!value) {
      this.externalAccount = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((Status)value);
      }
      break;

    case EXTERNAL_ACCOUNT:
      if (value == null) {
        unsetExternalAccount();
      } else {
        setExternalAccount((com.onesite.sdk.thrift.dao.ExternalAccount)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STATUS:
      return getStatus();

    case EXTERNAL_ACCOUNT:
      return getExternalAccount();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STATUS:
      return isSetStatus();
    case EXTERNAL_ACCOUNT:
      return isSetExternalAccount();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ResponseExternalAccount)
      return this.equals((ResponseExternalAccount)that);
    return false;
  }

  public boolean equals(ResponseExternalAccount that) {
    if (that == null)
      return false;

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (!this.status.equals(that.status))
        return false;
    }

    boolean this_present_externalAccount = true && this.isSetExternalAccount();
    boolean that_present_externalAccount = true && that.isSetExternalAccount();
    if (this_present_externalAccount || that_present_externalAccount) {
      if (!(this_present_externalAccount && that_present_externalAccount))
        return false;
      if (!this.externalAccount.equals(that.externalAccount))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_status = true && (isSetStatus());
    builder.append(present_status);
    if (present_status)
      builder.append(status);

    boolean present_externalAccount = true && (isSetExternalAccount());
    builder.append(present_externalAccount);
    if (present_externalAccount)
      builder.append(externalAccount);

    return builder.toHashCode();
  }

  public int compareTo(ResponseExternalAccount other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ResponseExternalAccount typedOther = (ResponseExternalAccount)other;

    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(typedOther.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, typedOther.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExternalAccount()).compareTo(typedOther.isSetExternalAccount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExternalAccount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.externalAccount, typedOther.externalAccount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ResponseExternalAccount(");
    boolean first = true;

    sb.append("status:");
    if (this.status == null) {
      sb.append("null");
    } else {
      sb.append(this.status);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("externalAccount:");
    if (this.externalAccount == null) {
      sb.append("null");
    } else {
      sb.append(this.externalAccount);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ResponseExternalAccountStandardSchemeFactory implements SchemeFactory {
    public ResponseExternalAccountStandardScheme getScheme() {
      return new ResponseExternalAccountStandardScheme();
    }
  }

  private static class ResponseExternalAccountStandardScheme extends StandardScheme<ResponseExternalAccount> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ResponseExternalAccount struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.status = new Status();
              struct.status.read(iprot);
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EXTERNAL_ACCOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.externalAccount = new com.onesite.sdk.thrift.dao.ExternalAccount();
              struct.externalAccount.read(iprot);
              struct.setExternalAccountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ResponseExternalAccount struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.status != null) {
        oprot.writeFieldBegin(STATUS_FIELD_DESC);
        struct.status.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.externalAccount != null) {
        oprot.writeFieldBegin(EXTERNAL_ACCOUNT_FIELD_DESC);
        struct.externalAccount.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ResponseExternalAccountTupleSchemeFactory implements SchemeFactory {
    public ResponseExternalAccountTupleScheme getScheme() {
      return new ResponseExternalAccountTupleScheme();
    }
  }

  private static class ResponseExternalAccountTupleScheme extends TupleScheme<ResponseExternalAccount> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ResponseExternalAccount struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetStatus()) {
        optionals.set(0);
      }
      if (struct.isSetExternalAccount()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetStatus()) {
        struct.status.write(oprot);
      }
      if (struct.isSetExternalAccount()) {
        struct.externalAccount.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ResponseExternalAccount struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.status = new Status();
        struct.status.read(iprot);
        struct.setStatusIsSet(true);
      }
      if (incoming.get(1)) {
        struct.externalAccount = new com.onesite.sdk.thrift.dao.ExternalAccount();
        struct.externalAccount.read(iprot);
        struct.setExternalAccountIsSet(true);
      }
    }
  }

}

