/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.onesite.sdk.thrift.api;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UserCreateOptions implements org.apache.thrift.TBase<UserCreateOptions, UserCreateOptions._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserCreateOptions");

  private static final org.apache.thrift.protocol.TField SEND_CONFIRMATION_EMAIL_FIELD_DESC = new org.apache.thrift.protocol.TField("sendConfirmationEmail", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField REFERRING_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("referringUrl", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ADD_INITIAL_FRIEND_FIELD_DESC = new org.apache.thrift.protocol.TField("addInitialFriend", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField JOIN_INITIAL_GROUP_FIELD_DESC = new org.apache.thrift.protocol.TField("joinInitialGroup", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField GROUP_MEMBER_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("groupMemberStatus", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField COUPON_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("couponCode", org.apache.thrift.protocol.TType.STRING, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UserCreateOptionsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UserCreateOptionsTupleSchemeFactory());
  }

  public boolean sendConfirmationEmail; // required
  public String referringUrl; // required
  public long addInitialFriend; // required
  public long joinInitialGroup; // required
  /**
   * 
   * @see com.onesite.sdk.thrift.dao.constants.GroupMemberStatus
   */
  public com.onesite.sdk.thrift.dao.constants.GroupMemberStatus groupMemberStatus; // required
  public String couponCode; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SEND_CONFIRMATION_EMAIL((short)1, "sendConfirmationEmail"),
    REFERRING_URL((short)2, "referringUrl"),
    ADD_INITIAL_FRIEND((short)3, "addInitialFriend"),
    JOIN_INITIAL_GROUP((short)4, "joinInitialGroup"),
    /**
     * 
     * @see com.onesite.sdk.thrift.dao.constants.GroupMemberStatus
     */
    GROUP_MEMBER_STATUS((short)5, "groupMemberStatus"),
    COUPON_CODE((short)6, "couponCode");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SEND_CONFIRMATION_EMAIL
          return SEND_CONFIRMATION_EMAIL;
        case 2: // REFERRING_URL
          return REFERRING_URL;
        case 3: // ADD_INITIAL_FRIEND
          return ADD_INITIAL_FRIEND;
        case 4: // JOIN_INITIAL_GROUP
          return JOIN_INITIAL_GROUP;
        case 5: // GROUP_MEMBER_STATUS
          return GROUP_MEMBER_STATUS;
        case 6: // COUPON_CODE
          return COUPON_CODE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SENDCONFIRMATIONEMAIL_ISSET_ID = 0;
  private static final int __ADDINITIALFRIEND_ISSET_ID = 1;
  private static final int __JOININITIALGROUP_ISSET_ID = 2;
  private BitSet __isset_bit_vector = new BitSet(3);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SEND_CONFIRMATION_EMAIL, new org.apache.thrift.meta_data.FieldMetaData("sendConfirmationEmail", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.REFERRING_URL, new org.apache.thrift.meta_data.FieldMetaData("referringUrl", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ADD_INITIAL_FRIEND, new org.apache.thrift.meta_data.FieldMetaData("addInitialFriend", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.JOIN_INITIAL_GROUP, new org.apache.thrift.meta_data.FieldMetaData("joinInitialGroup", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.GROUP_MEMBER_STATUS, new org.apache.thrift.meta_data.FieldMetaData("groupMemberStatus", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, com.onesite.sdk.thrift.dao.constants.GroupMemberStatus.class)));
    tmpMap.put(_Fields.COUPON_CODE, new org.apache.thrift.meta_data.FieldMetaData("couponCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserCreateOptions.class, metaDataMap);
  }

  public UserCreateOptions() {
  }

  public UserCreateOptions(
    boolean sendConfirmationEmail,
    String referringUrl,
    long addInitialFriend,
    long joinInitialGroup,
    com.onesite.sdk.thrift.dao.constants.GroupMemberStatus groupMemberStatus,
    String couponCode)
  {
    this();
    this.sendConfirmationEmail = sendConfirmationEmail;
    setSendConfirmationEmailIsSet(true);
    this.referringUrl = referringUrl;
    this.addInitialFriend = addInitialFriend;
    setAddInitialFriendIsSet(true);
    this.joinInitialGroup = joinInitialGroup;
    setJoinInitialGroupIsSet(true);
    this.groupMemberStatus = groupMemberStatus;
    this.couponCode = couponCode;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserCreateOptions(UserCreateOptions other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.sendConfirmationEmail = other.sendConfirmationEmail;
    if (other.isSetReferringUrl()) {
      this.referringUrl = other.referringUrl;
    }
    this.addInitialFriend = other.addInitialFriend;
    this.joinInitialGroup = other.joinInitialGroup;
    if (other.isSetGroupMemberStatus()) {
      this.groupMemberStatus = other.groupMemberStatus;
    }
    if (other.isSetCouponCode()) {
      this.couponCode = other.couponCode;
    }
  }

  public UserCreateOptions deepCopy() {
    return new UserCreateOptions(this);
  }

  @Override
  public void clear() {
    setSendConfirmationEmailIsSet(false);
    this.sendConfirmationEmail = false;
    this.referringUrl = null;
    setAddInitialFriendIsSet(false);
    this.addInitialFriend = 0;
    setJoinInitialGroupIsSet(false);
    this.joinInitialGroup = 0;
    this.groupMemberStatus = null;
    this.couponCode = null;
  }

  public boolean isSendConfirmationEmail() {
    return this.sendConfirmationEmail;
  }

  public UserCreateOptions setSendConfirmationEmail(boolean sendConfirmationEmail) {
    this.sendConfirmationEmail = sendConfirmationEmail;
    setSendConfirmationEmailIsSet(true);
    return this;
  }

  public void unsetSendConfirmationEmail() {
    __isset_bit_vector.clear(__SENDCONFIRMATIONEMAIL_ISSET_ID);
  }

  /** Returns true if field sendConfirmationEmail is set (has been assigned a value) and false otherwise */
  public boolean isSetSendConfirmationEmail() {
    return __isset_bit_vector.get(__SENDCONFIRMATIONEMAIL_ISSET_ID);
  }

  public void setSendConfirmationEmailIsSet(boolean value) {
    __isset_bit_vector.set(__SENDCONFIRMATIONEMAIL_ISSET_ID, value);
  }

  public String getReferringUrl() {
    return this.referringUrl;
  }

  public UserCreateOptions setReferringUrl(String referringUrl) {
    this.referringUrl = referringUrl;
    return this;
  }

  public void unsetReferringUrl() {
    this.referringUrl = null;
  }

  /** Returns true if field referringUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetReferringUrl() {
    return this.referringUrl != null;
  }

  public void setReferringUrlIsSet(boolean value) {
    if (!value) {
      this.referringUrl = null;
    }
  }

  public long getAddInitialFriend() {
    return this.addInitialFriend;
  }

  public UserCreateOptions setAddInitialFriend(long addInitialFriend) {
    this.addInitialFriend = addInitialFriend;
    setAddInitialFriendIsSet(true);
    return this;
  }

  public void unsetAddInitialFriend() {
    __isset_bit_vector.clear(__ADDINITIALFRIEND_ISSET_ID);
  }

  /** Returns true if field addInitialFriend is set (has been assigned a value) and false otherwise */
  public boolean isSetAddInitialFriend() {
    return __isset_bit_vector.get(__ADDINITIALFRIEND_ISSET_ID);
  }

  public void setAddInitialFriendIsSet(boolean value) {
    __isset_bit_vector.set(__ADDINITIALFRIEND_ISSET_ID, value);
  }

  public long getJoinInitialGroup() {
    return this.joinInitialGroup;
  }

  public UserCreateOptions setJoinInitialGroup(long joinInitialGroup) {
    this.joinInitialGroup = joinInitialGroup;
    setJoinInitialGroupIsSet(true);
    return this;
  }

  public void unsetJoinInitialGroup() {
    __isset_bit_vector.clear(__JOININITIALGROUP_ISSET_ID);
  }

  /** Returns true if field joinInitialGroup is set (has been assigned a value) and false otherwise */
  public boolean isSetJoinInitialGroup() {
    return __isset_bit_vector.get(__JOININITIALGROUP_ISSET_ID);
  }

  public void setJoinInitialGroupIsSet(boolean value) {
    __isset_bit_vector.set(__JOININITIALGROUP_ISSET_ID, value);
  }

  /**
   * 
   * @see com.onesite.sdk.thrift.dao.constants.GroupMemberStatus
   */
  public com.onesite.sdk.thrift.dao.constants.GroupMemberStatus getGroupMemberStatus() {
    return this.groupMemberStatus;
  }

  /**
   * 
   * @see com.onesite.sdk.thrift.dao.constants.GroupMemberStatus
   */
  public UserCreateOptions setGroupMemberStatus(com.onesite.sdk.thrift.dao.constants.GroupMemberStatus groupMemberStatus) {
    this.groupMemberStatus = groupMemberStatus;
    return this;
  }

  public void unsetGroupMemberStatus() {
    this.groupMemberStatus = null;
  }

  /** Returns true if field groupMemberStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetGroupMemberStatus() {
    return this.groupMemberStatus != null;
  }

  public void setGroupMemberStatusIsSet(boolean value) {
    if (!value) {
      this.groupMemberStatus = null;
    }
  }

  public String getCouponCode() {
    return this.couponCode;
  }

  public UserCreateOptions setCouponCode(String couponCode) {
    this.couponCode = couponCode;
    return this;
  }

  public void unsetCouponCode() {
    this.couponCode = null;
  }

  /** Returns true if field couponCode is set (has been assigned a value) and false otherwise */
  public boolean isSetCouponCode() {
    return this.couponCode != null;
  }

  public void setCouponCodeIsSet(boolean value) {
    if (!value) {
      this.couponCode = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SEND_CONFIRMATION_EMAIL:
      if (value == null) {
        unsetSendConfirmationEmail();
      } else {
        setSendConfirmationEmail((Boolean)value);
      }
      break;

    case REFERRING_URL:
      if (value == null) {
        unsetReferringUrl();
      } else {
        setReferringUrl((String)value);
      }
      break;

    case ADD_INITIAL_FRIEND:
      if (value == null) {
        unsetAddInitialFriend();
      } else {
        setAddInitialFriend((Long)value);
      }
      break;

    case JOIN_INITIAL_GROUP:
      if (value == null) {
        unsetJoinInitialGroup();
      } else {
        setJoinInitialGroup((Long)value);
      }
      break;

    case GROUP_MEMBER_STATUS:
      if (value == null) {
        unsetGroupMemberStatus();
      } else {
        setGroupMemberStatus((com.onesite.sdk.thrift.dao.constants.GroupMemberStatus)value);
      }
      break;

    case COUPON_CODE:
      if (value == null) {
        unsetCouponCode();
      } else {
        setCouponCode((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SEND_CONFIRMATION_EMAIL:
      return Boolean.valueOf(isSendConfirmationEmail());

    case REFERRING_URL:
      return getReferringUrl();

    case ADD_INITIAL_FRIEND:
      return Long.valueOf(getAddInitialFriend());

    case JOIN_INITIAL_GROUP:
      return Long.valueOf(getJoinInitialGroup());

    case GROUP_MEMBER_STATUS:
      return getGroupMemberStatus();

    case COUPON_CODE:
      return getCouponCode();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SEND_CONFIRMATION_EMAIL:
      return isSetSendConfirmationEmail();
    case REFERRING_URL:
      return isSetReferringUrl();
    case ADD_INITIAL_FRIEND:
      return isSetAddInitialFriend();
    case JOIN_INITIAL_GROUP:
      return isSetJoinInitialGroup();
    case GROUP_MEMBER_STATUS:
      return isSetGroupMemberStatus();
    case COUPON_CODE:
      return isSetCouponCode();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UserCreateOptions)
      return this.equals((UserCreateOptions)that);
    return false;
  }

  public boolean equals(UserCreateOptions that) {
    if (that == null)
      return false;

    boolean this_present_sendConfirmationEmail = true;
    boolean that_present_sendConfirmationEmail = true;
    if (this_present_sendConfirmationEmail || that_present_sendConfirmationEmail) {
      if (!(this_present_sendConfirmationEmail && that_present_sendConfirmationEmail))
        return false;
      if (this.sendConfirmationEmail != that.sendConfirmationEmail)
        return false;
    }

    boolean this_present_referringUrl = true && this.isSetReferringUrl();
    boolean that_present_referringUrl = true && that.isSetReferringUrl();
    if (this_present_referringUrl || that_present_referringUrl) {
      if (!(this_present_referringUrl && that_present_referringUrl))
        return false;
      if (!this.referringUrl.equals(that.referringUrl))
        return false;
    }

    boolean this_present_addInitialFriend = true;
    boolean that_present_addInitialFriend = true;
    if (this_present_addInitialFriend || that_present_addInitialFriend) {
      if (!(this_present_addInitialFriend && that_present_addInitialFriend))
        return false;
      if (this.addInitialFriend != that.addInitialFriend)
        return false;
    }

    boolean this_present_joinInitialGroup = true;
    boolean that_present_joinInitialGroup = true;
    if (this_present_joinInitialGroup || that_present_joinInitialGroup) {
      if (!(this_present_joinInitialGroup && that_present_joinInitialGroup))
        return false;
      if (this.joinInitialGroup != that.joinInitialGroup)
        return false;
    }

    boolean this_present_groupMemberStatus = true && this.isSetGroupMemberStatus();
    boolean that_present_groupMemberStatus = true && that.isSetGroupMemberStatus();
    if (this_present_groupMemberStatus || that_present_groupMemberStatus) {
      if (!(this_present_groupMemberStatus && that_present_groupMemberStatus))
        return false;
      if (!this.groupMemberStatus.equals(that.groupMemberStatus))
        return false;
    }

    boolean this_present_couponCode = true && this.isSetCouponCode();
    boolean that_present_couponCode = true && that.isSetCouponCode();
    if (this_present_couponCode || that_present_couponCode) {
      if (!(this_present_couponCode && that_present_couponCode))
        return false;
      if (!this.couponCode.equals(that.couponCode))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_sendConfirmationEmail = true;
    builder.append(present_sendConfirmationEmail);
    if (present_sendConfirmationEmail)
      builder.append(sendConfirmationEmail);

    boolean present_referringUrl = true && (isSetReferringUrl());
    builder.append(present_referringUrl);
    if (present_referringUrl)
      builder.append(referringUrl);

    boolean present_addInitialFriend = true;
    builder.append(present_addInitialFriend);
    if (present_addInitialFriend)
      builder.append(addInitialFriend);

    boolean present_joinInitialGroup = true;
    builder.append(present_joinInitialGroup);
    if (present_joinInitialGroup)
      builder.append(joinInitialGroup);

    boolean present_groupMemberStatus = true && (isSetGroupMemberStatus());
    builder.append(present_groupMemberStatus);
    if (present_groupMemberStatus)
      builder.append(groupMemberStatus.getValue());

    boolean present_couponCode = true && (isSetCouponCode());
    builder.append(present_couponCode);
    if (present_couponCode)
      builder.append(couponCode);

    return builder.toHashCode();
  }

  public int compareTo(UserCreateOptions other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    UserCreateOptions typedOther = (UserCreateOptions)other;

    lastComparison = Boolean.valueOf(isSetSendConfirmationEmail()).compareTo(typedOther.isSetSendConfirmationEmail());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSendConfirmationEmail()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sendConfirmationEmail, typedOther.sendConfirmationEmail);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReferringUrl()).compareTo(typedOther.isSetReferringUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReferringUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.referringUrl, typedOther.referringUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAddInitialFriend()).compareTo(typedOther.isSetAddInitialFriend());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAddInitialFriend()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.addInitialFriend, typedOther.addInitialFriend);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetJoinInitialGroup()).compareTo(typedOther.isSetJoinInitialGroup());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJoinInitialGroup()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.joinInitialGroup, typedOther.joinInitialGroup);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetGroupMemberStatus()).compareTo(typedOther.isSetGroupMemberStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGroupMemberStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.groupMemberStatus, typedOther.groupMemberStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCouponCode()).compareTo(typedOther.isSetCouponCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCouponCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.couponCode, typedOther.couponCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserCreateOptions(");
    boolean first = true;

    sb.append("sendConfirmationEmail:");
    sb.append(this.sendConfirmationEmail);
    first = false;
    if (!first) sb.append(", ");
    sb.append("referringUrl:");
    if (this.referringUrl == null) {
      sb.append("null");
    } else {
      sb.append(this.referringUrl);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("addInitialFriend:");
    sb.append(this.addInitialFriend);
    first = false;
    if (!first) sb.append(", ");
    sb.append("joinInitialGroup:");
    sb.append(this.joinInitialGroup);
    first = false;
    if (!first) sb.append(", ");
    sb.append("groupMemberStatus:");
    if (this.groupMemberStatus == null) {
      sb.append("null");
    } else {
      sb.append(this.groupMemberStatus);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("couponCode:");
    if (this.couponCode == null) {
      sb.append("null");
    } else {
      sb.append(this.couponCode);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserCreateOptionsStandardSchemeFactory implements SchemeFactory {
    public UserCreateOptionsStandardScheme getScheme() {
      return new UserCreateOptionsStandardScheme();
    }
  }

  private static class UserCreateOptionsStandardScheme extends StandardScheme<UserCreateOptions> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserCreateOptions struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SEND_CONFIRMATION_EMAIL
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.sendConfirmationEmail = iprot.readBool();
              struct.setSendConfirmationEmailIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // REFERRING_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.referringUrl = iprot.readString();
              struct.setReferringUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ADD_INITIAL_FRIEND
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.addInitialFriend = iprot.readI64();
              struct.setAddInitialFriendIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // JOIN_INITIAL_GROUP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.joinInitialGroup = iprot.readI64();
              struct.setJoinInitialGroupIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // GROUP_MEMBER_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.groupMemberStatus = com.onesite.sdk.thrift.dao.constants.GroupMemberStatus.findByValue(iprot.readI32());
              struct.setGroupMemberStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // COUPON_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.couponCode = iprot.readString();
              struct.setCouponCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserCreateOptions struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SEND_CONFIRMATION_EMAIL_FIELD_DESC);
      oprot.writeBool(struct.sendConfirmationEmail);
      oprot.writeFieldEnd();
      if (struct.referringUrl != null) {
        oprot.writeFieldBegin(REFERRING_URL_FIELD_DESC);
        oprot.writeString(struct.referringUrl);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ADD_INITIAL_FRIEND_FIELD_DESC);
      oprot.writeI64(struct.addInitialFriend);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(JOIN_INITIAL_GROUP_FIELD_DESC);
      oprot.writeI64(struct.joinInitialGroup);
      oprot.writeFieldEnd();
      if (struct.groupMemberStatus != null) {
        oprot.writeFieldBegin(GROUP_MEMBER_STATUS_FIELD_DESC);
        oprot.writeI32(struct.groupMemberStatus.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.couponCode != null) {
        oprot.writeFieldBegin(COUPON_CODE_FIELD_DESC);
        oprot.writeString(struct.couponCode);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserCreateOptionsTupleSchemeFactory implements SchemeFactory {
    public UserCreateOptionsTupleScheme getScheme() {
      return new UserCreateOptionsTupleScheme();
    }
  }

  private static class UserCreateOptionsTupleScheme extends TupleScheme<UserCreateOptions> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserCreateOptions struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSendConfirmationEmail()) {
        optionals.set(0);
      }
      if (struct.isSetReferringUrl()) {
        optionals.set(1);
      }
      if (struct.isSetAddInitialFriend()) {
        optionals.set(2);
      }
      if (struct.isSetJoinInitialGroup()) {
        optionals.set(3);
      }
      if (struct.isSetGroupMemberStatus()) {
        optionals.set(4);
      }
      if (struct.isSetCouponCode()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetSendConfirmationEmail()) {
        oprot.writeBool(struct.sendConfirmationEmail);
      }
      if (struct.isSetReferringUrl()) {
        oprot.writeString(struct.referringUrl);
      }
      if (struct.isSetAddInitialFriend()) {
        oprot.writeI64(struct.addInitialFriend);
      }
      if (struct.isSetJoinInitialGroup()) {
        oprot.writeI64(struct.joinInitialGroup);
      }
      if (struct.isSetGroupMemberStatus()) {
        oprot.writeI32(struct.groupMemberStatus.getValue());
      }
      if (struct.isSetCouponCode()) {
        oprot.writeString(struct.couponCode);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserCreateOptions struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.sendConfirmationEmail = iprot.readBool();
        struct.setSendConfirmationEmailIsSet(true);
      }
      if (incoming.get(1)) {
        struct.referringUrl = iprot.readString();
        struct.setReferringUrlIsSet(true);
      }
      if (incoming.get(2)) {
        struct.addInitialFriend = iprot.readI64();
        struct.setAddInitialFriendIsSet(true);
      }
      if (incoming.get(3)) {
        struct.joinInitialGroup = iprot.readI64();
        struct.setJoinInitialGroupIsSet(true);
      }
      if (incoming.get(4)) {
        struct.groupMemberStatus = com.onesite.sdk.thrift.dao.constants.GroupMemberStatus.findByValue(iprot.readI32());
        struct.setGroupMemberStatusIsSet(true);
      }
      if (incoming.get(5)) {
        struct.couponCode = iprot.readString();
        struct.setCouponCodeIsSet(true);
      }
    }
  }

}

